### ISSUE TITLE
Using Linode/lamp

### ISSUE THREAD

**Issue by aug-riedinger** [tkyk/docker-compose-lamp#1]
Why not using this base image?

https://hub.docker.com/r/linode/lamp/

As this seem to be the official one?

I'm trying to figure out a config out of it, but I can't make it work:

Dockerfile:
```
FROM linode/lamp
RUN service apache2 start
RUN service mysql start
```

docker-compose.yml:
```
web:
  build: .
  ports:
    - "80:80"
  volumes:
    - .:/var/www/example.com/public_html/
```

Any idea what's wrong?
